let word="Hello"
console.log(word.length)
console.log(word.toUpperCase())
console.log(word.toLowerCase())
console.log(word.concat(" ","world"))
console.log(word.includes("e"))
console.log(word.indexOf("e"))
console.log(word.charAt(2))
console.log(word.lastIndexOf("l"))
console.log(word.startsWith("H"))
console.log(word.replace("H","p"))
console.log(word.slice(1,4))
console.log(word.split(","))
console.log(word.repeat(6))
console.log(word.trim())
console.log(word.trimStart())
console.log(word.trimEnd())